import type { Category } from './types';

export interface PresetMachine {
	name: string;
	category: Category;
	defaultWeight?: number;
}

export const presetMachines: Record<Category, PresetMachine[]> = {
	legs: [
		{ name: 'Leg Press', category: 'legs', defaultWeight: 60 },
		{ name: 'Leg Curl', category: 'legs', defaultWeight: 25 },
		{ name: 'Seated Leg Curl', category: 'legs', defaultWeight: 25 },
		{ name: 'Lying Leg Curl', category: 'legs', defaultWeight: 20 },
		{ name: 'Standing Leg Curl', category: 'legs', defaultWeight: 15 },
		{ name: 'Leg Extension', category: 'legs', defaultWeight: 30 },
		{ name: 'Calf Raise', category: 'legs', defaultWeight: 40 },
		{ name: 'Seated Calf Raise', category: 'legs', defaultWeight: 30 },
		{ name: 'Standing Calf Raise', category: 'legs', defaultWeight: 50 },
		{ name: 'Hip Abductor', category: 'legs', defaultWeight: 35 },
		{ name: 'Hip Adductor', category: 'legs', defaultWeight: 35 },
		{ name: 'Hack Squat', category: 'legs', defaultWeight: 40 },
		{ name: 'Pendulum Squat', category: 'legs', defaultWeight: 40 },
		{ name: 'V-Squat', category: 'legs', defaultWeight: 40 },
		{ name: 'Belt Squat', category: 'legs', defaultWeight: 40 },
		{ name: 'Smith Machine Squat', category: 'legs', defaultWeight: 20 },
		{ name: 'Glute Kickback', category: 'legs', defaultWeight: 20 },
		{ name: 'Glute Machine', category: 'legs', defaultWeight: 30 },
		{ name: 'Glute Drive', category: 'legs', defaultWeight: 50 },
		{ name: 'Squats', category: 'legs', defaultWeight: 20 },
		{ name: 'Front Squat', category: 'legs', defaultWeight: 30 },
		{ name: 'Sumo Squat', category: 'legs', defaultWeight: 20 },
		{ name: 'Sissy Squat', category: 'legs', defaultWeight: 0 },
		{ name: 'Lunges', category: 'legs', defaultWeight: 10 },
		{ name: 'Walking Lunges', category: 'legs', defaultWeight: 10 },
		{ name: 'Reverse Lunges', category: 'legs', defaultWeight: 10 },
		{ name: 'Romanian Deadlift', category: 'legs', defaultWeight: 30 },
		{ name: 'Stiff Leg Deadlift', category: 'legs', defaultWeight: 30 },
		{ name: 'Single Leg Romanian Deadlift', category: 'legs', defaultWeight: 10 },
		{ name: 'Bulgarian Split Squat', category: 'legs', defaultWeight: 10 },
		{ name: 'Goblet Squat', category: 'legs', defaultWeight: 16 },
		{ name: 'Hip Thrust', category: 'legs', defaultWeight: 40 },
		{ name: 'Barbell Hip Thrust', category: 'legs', defaultWeight: 60 },
		{ name: 'Deadlift', category: 'legs', defaultWeight: 40 },
		{ name: 'Sumo Deadlift', category: 'legs', defaultWeight: 50 },
		{ name: 'Trap Bar Deadlift', category: 'legs', defaultWeight: 50 },
		{ name: 'Good Mornings', category: 'legs', defaultWeight: 20 },
		{ name: 'Nordic Curl', category: 'legs', defaultWeight: 0 },
		{ name: 'Reverse Hyperextension', category: 'legs', defaultWeight: 0 },
		{ name: 'Step Ups', category: 'legs', defaultWeight: 10 },
		{ name: 'Box Squat', category: 'legs', defaultWeight: 30 }
	],
	chest: [
		{ name: 'Chest Press', category: 'chest', defaultWeight: 30 },
		{ name: 'Chest Press Machine', category: 'chest', defaultWeight: 40 },
		{ name: 'Incline Press', category: 'chest', defaultWeight: 25 },
		{ name: 'Incline Chest Press Machine', category: 'chest', defaultWeight: 35 },
		{ name: 'Decline Press', category: 'chest', defaultWeight: 30 },
		{ name: 'Pec Fly', category: 'chest', defaultWeight: 20 },
		{ name: 'Pec Deck', category: 'chest', defaultWeight: 25 },
		{ name: 'Pec Deck Rear Delt Combo', category: 'chest', defaultWeight: 20 },
		{ name: 'Cable Crossover', category: 'chest', defaultWeight: 15 },
		{ name: 'Low Cable Crossover', category: 'chest', defaultWeight: 10 },
		{ name: 'High Cable Crossover', category: 'chest', defaultWeight: 10 },
		{ name: 'Cable Fly', category: 'chest', defaultWeight: 10 },
		{ name: 'Dumbbell Bench Press', category: 'chest', defaultWeight: 12 },
		{ name: 'Dumbbell Incline Press', category: 'chest', defaultWeight: 10 },
		{ name: 'Dumbbell Decline Press', category: 'chest', defaultWeight: 12 },
		{ name: 'Dumbbell Fly', category: 'chest', defaultWeight: 8 },
		{ name: 'Incline Dumbbell Fly', category: 'chest', defaultWeight: 8 },
		{ name: 'Barbell Bench Press', category: 'chest', defaultWeight: 40 },
		{ name: 'Barbell Incline Press', category: 'chest', defaultWeight: 30 },
		{ name: 'Barbell Decline Press', category: 'chest', defaultWeight: 40 },
		{ name: 'Smith Machine Bench Press', category: 'chest', defaultWeight: 30 },
		{ name: 'Smith Machine Incline Press', category: 'chest', defaultWeight: 25 },
		{ name: 'Push-ups', category: 'chest', defaultWeight: 0 },
		{ name: 'Incline Push-ups', category: 'chest', defaultWeight: 0 },
		{ name: 'Decline Push-ups', category: 'chest', defaultWeight: 0 },
		{ name: 'Diamond Push-ups', category: 'chest', defaultWeight: 0 },
		{ name: 'Wide Push-ups', category: 'chest', defaultWeight: 0 },
		{ name: 'Chest Dips', category: 'chest', defaultWeight: 0 },
		{ name: 'Assisted Chest Dips', category: 'chest', defaultWeight: 20 },
		{ name: 'Landmine Press', category: 'chest', defaultWeight: 20 },
		{ name: 'Floor Press', category: 'chest', defaultWeight: 30 },
		{ name: 'Svend Press', category: 'chest', defaultWeight: 10 }
	],
	back: [
		// Lat Pulldown variations
		{ name: 'Lat Pulldown', category: 'back', defaultWeight: 35 },
		{ name: 'Divergent Lat Pulldown', category: 'back', defaultWeight: 30 },
		{ name: 'Wide Grip Lat Pulldown', category: 'back', defaultWeight: 35 },
		{ name: 'Close Grip Lat Pulldown', category: 'back', defaultWeight: 35 },
		{ name: 'Reverse Grip Lat Pulldown', category: 'back', defaultWeight: 30 },
		{ name: 'Neutral Grip Lat Pulldown', category: 'back', defaultWeight: 35 },
		{ name: 'Single Arm Lat Pulldown', category: 'back', defaultWeight: 20 },
		{ name: 'Behind Neck Lat Pulldown', category: 'back', defaultWeight: 30 },
		{ name: 'Chest Pulldown', category: 'back', defaultWeight: 30 },
		// Row variations
		{ name: 'Seated Row', category: 'back', defaultWeight: 40 },
		{ name: 'Seated Row Machine', category: 'back', defaultWeight: 45 },
		{ name: 'Low Row', category: 'back', defaultWeight: 35 },
		{ name: 'Low Row Machine', category: 'back', defaultWeight: 40 },
		{ name: 'Cable Row', category: 'back', defaultWeight: 35 },
		{ name: 'High Row', category: 'back', defaultWeight: 35 },
		{ name: 'High Row Machine', category: 'back', defaultWeight: 40 },
		{ name: 'Single Arm Cable Row', category: 'back', defaultWeight: 20 },
		{ name: 'Wide Grip Seated Row', category: 'back', defaultWeight: 35 },
		{ name: 'Close Grip Seated Row', category: 'back', defaultWeight: 40 },
		{ name: 'Chest Supported Row', category: 'back', defaultWeight: 25 },
		{ name: 'Chest Supported Row Machine', category: 'back', defaultWeight: 35 },
		{ name: 'Incline Row', category: 'back', defaultWeight: 20 },
		{ name: 'Pendlay Row', category: 'back', defaultWeight: 40 },
		{ name: 'Meadows Row', category: 'back', defaultWeight: 20 },
		{ name: 'Seal Row', category: 'back', defaultWeight: 25 },
		{ name: 'Helms Row', category: 'back', defaultWeight: 15 },
		// T-Bar and Barbell rows
		{ name: 'T-Bar Row', category: 'back', defaultWeight: 20 },
		{ name: 'Barbell Row', category: 'back', defaultWeight: 30 },
		{ name: 'Dumbbell Row', category: 'back', defaultWeight: 12 },
		{ name: 'Single Arm Dumbbell Row', category: 'back', defaultWeight: 15 },
		{ name: 'Kroc Row', category: 'back', defaultWeight: 25 },
		// Pull-up variations
		{ name: 'Pull-ups', category: 'back', defaultWeight: 0 },
		{ name: 'Wide Grip Pull-ups', category: 'back', defaultWeight: 0 },
		{ name: 'Close Grip Pull-ups', category: 'back', defaultWeight: 0 },
		{ name: 'Chin-ups', category: 'back', defaultWeight: 0 },
		{ name: 'Neutral Grip Pull-ups', category: 'back', defaultWeight: 0 },
		{ name: 'Assisted Pull-up', category: 'back', defaultWeight: 30 },
		{ name: 'Assisted Chin-up', category: 'back', defaultWeight: 30 },
		{ name: 'Weighted Pull-ups', category: 'back', defaultWeight: 10 },
		// Other back exercises
		{ name: 'Back Extension', category: 'back', defaultWeight: 0 },
		{ name: 'Hyperextension', category: 'back', defaultWeight: 0 },
		{ name: '45 Degree Back Extension', category: 'back', defaultWeight: 0 },
		{ name: 'Reverse Fly', category: 'back', defaultWeight: 10 },
		{ name: 'Reverse Fly Machine', category: 'back', defaultWeight: 15 },
		{ name: 'Face Pull', category: 'back', defaultWeight: 15 },
		{ name: 'Straight Arm Pulldown', category: 'back', defaultWeight: 20 },
		{ name: 'Pullover', category: 'back', defaultWeight: 15 },
		{ name: 'Dumbbell Pullover', category: 'back', defaultWeight: 15 },
		{ name: 'Cable Pullover', category: 'back', defaultWeight: 20 },
		{ name: 'Pullover Machine', category: 'back', defaultWeight: 30 },
		{ name: 'Inverted Row', category: 'back', defaultWeight: 0 },
		{ name: 'Rack Pull', category: 'back', defaultWeight: 60 },
		{ name: 'Shrugs', category: 'back', defaultWeight: 20 },
		{ name: 'Barbell Shrugs', category: 'back', defaultWeight: 40 },
		{ name: 'Dumbbell Shrugs', category: 'back', defaultWeight: 20 }
	],
	shoulders: [
		// Pressing movements
		{ name: 'Shoulder Press', category: 'shoulders', defaultWeight: 20 },
		{ name: 'Shoulder Press Machine', category: 'shoulders', defaultWeight: 30 },
		{ name: 'Dumbbell Shoulder Press', category: 'shoulders', defaultWeight: 10 },
		{ name: 'Seated Dumbbell Press', category: 'shoulders', defaultWeight: 12 },
		{ name: 'Standing Dumbbell Press', category: 'shoulders', defaultWeight: 10 },
		{ name: 'Barbell Shoulder Press', category: 'shoulders', defaultWeight: 30 },
		{ name: 'Military Press', category: 'shoulders', defaultWeight: 30 },
		{ name: 'Overhead Press', category: 'shoulders', defaultWeight: 30 },
		{ name: 'Push Press', category: 'shoulders', defaultWeight: 35 },
		{ name: 'Arnold Press', category: 'shoulders', defaultWeight: 10 },
		{ name: 'Smith Machine Shoulder Press', category: 'shoulders', defaultWeight: 25 },
		{ name: 'Behind Neck Press', category: 'shoulders', defaultWeight: 20 },
		{ name: 'Landmine Press', category: 'shoulders', defaultWeight: 20 },
		{ name: 'Single Arm Landmine Press', category: 'shoulders', defaultWeight: 15 },
		// Lateral raises
		{ name: 'Lateral Raise', category: 'shoulders', defaultWeight: 8 },
		{ name: 'Dumbbell Lateral Raise', category: 'shoulders', defaultWeight: 8 },
		{ name: 'Cable Lateral Raise', category: 'shoulders', defaultWeight: 5 },
		{ name: 'Machine Lateral Raise', category: 'shoulders', defaultWeight: 15 },
		{ name: 'Leaning Lateral Raise', category: 'shoulders', defaultWeight: 6 },
		{ name: 'Incline Lateral Raise', category: 'shoulders', defaultWeight: 5 },
		// Front raises
		{ name: 'Front Raise', category: 'shoulders', defaultWeight: 6 },
		{ name: 'Dumbbell Front Raise', category: 'shoulders', defaultWeight: 6 },
		{ name: 'Cable Front Raise', category: 'shoulders', defaultWeight: 8 },
		{ name: 'Plate Front Raise', category: 'shoulders', defaultWeight: 10 },
		{ name: 'Barbell Front Raise', category: 'shoulders', defaultWeight: 15 },
		// Rear delt
		{ name: 'Rear Delt Fly', category: 'shoulders', defaultWeight: 10 },
		{ name: 'Rear Delt Fly Machine', category: 'shoulders', defaultWeight: 15 },
		{ name: 'Bent Over Rear Delt Fly', category: 'shoulders', defaultWeight: 6 },
		{ name: 'Cable Rear Delt Fly', category: 'shoulders', defaultWeight: 8 },
		{ name: 'Face Pull', category: 'shoulders', defaultWeight: 15 },
		// Upright rows and shrugs
		{ name: 'Upright Row', category: 'shoulders', defaultWeight: 15 },
		{ name: 'Dumbbell Upright Row', category: 'shoulders', defaultWeight: 10 },
		{ name: 'Cable Upright Row', category: 'shoulders', defaultWeight: 15 },
		{ name: 'Shrugs', category: 'shoulders', defaultWeight: 20 },
		// Other shoulder exercises
		{ name: 'Y Raise', category: 'shoulders', defaultWeight: 4 },
		{ name: 'W Raise', category: 'shoulders', defaultWeight: 4 },
		{ name: 'Lu Raise', category: 'shoulders', defaultWeight: 4 },
		{ name: 'External Rotation', category: 'shoulders', defaultWeight: 5 },
		{ name: 'Internal Rotation', category: 'shoulders', defaultWeight: 5 },
		{ name: 'Cuban Press', category: 'shoulders', defaultWeight: 8 },
		{ name: 'Handstand Push-ups', category: 'shoulders', defaultWeight: 0 },
		{ name: 'Pike Push-ups', category: 'shoulders', defaultWeight: 0 }
	],
	arms: [
		// Bicep exercises
		{ name: 'Bicep Curl', category: 'arms', defaultWeight: 10 },
		{ name: 'Dumbbell Curl', category: 'arms', defaultWeight: 8 },
		{ name: 'Barbell Curl', category: 'arms', defaultWeight: 20 },
		{ name: 'EZ Bar Curl', category: 'arms', defaultWeight: 15 },
		{ name: 'Hammer Curl', category: 'arms', defaultWeight: 10 },
		{ name: 'Preacher Curl', category: 'arms', defaultWeight: 15 },
		{ name: 'Preacher Curl Machine', category: 'arms', defaultWeight: 20 },
		{ name: 'Cable Curl', category: 'arms', defaultWeight: 15 },
		{ name: 'Rope Cable Curl', category: 'arms', defaultWeight: 15 },
		{ name: 'Concentration Curl', category: 'arms', defaultWeight: 8 },
		{ name: 'Incline Dumbbell Curl', category: 'arms', defaultWeight: 8 },
		{ name: 'Spider Curl', category: 'arms', defaultWeight: 8 },
		{ name: 'Drag Curl', category: 'arms', defaultWeight: 15 },
		{ name: 'Zottman Curl', category: 'arms', defaultWeight: 8 },
		{ name: 'Reverse Curl', category: 'arms', defaultWeight: 10 },
		{ name: 'Cable Hammer Curl', category: 'arms', defaultWeight: 15 },
		{ name: 'Machine Bicep Curl', category: 'arms', defaultWeight: 20 },
		{ name: '21s Bicep Curl', category: 'arms', defaultWeight: 10 },
		// Tricep exercises
		{ name: 'Tricep Pushdown', category: 'arms', defaultWeight: 20 },
		{ name: 'Rope Tricep Pushdown', category: 'arms', defaultWeight: 18 },
		{ name: 'V-Bar Tricep Pushdown', category: 'arms', defaultWeight: 22 },
		{ name: 'Single Arm Tricep Pushdown', category: 'arms', defaultWeight: 10 },
		{ name: 'Tricep Extension', category: 'arms', defaultWeight: 15 },
		{ name: 'Overhead Tricep Extension', category: 'arms', defaultWeight: 12 },
		{ name: 'Overhead Cable Tricep Extension', category: 'arms', defaultWeight: 15 },
		{ name: 'Dumbbell Tricep Extension', category: 'arms', defaultWeight: 10 },
		{ name: 'Single Arm Overhead Tricep Extension', category: 'arms', defaultWeight: 8 },
		{ name: 'Tricep Dips', category: 'arms', defaultWeight: 0 },
		{ name: 'Assisted Tricep Dips', category: 'arms', defaultWeight: 25 },
		{ name: 'Bench Dips', category: 'arms', defaultWeight: 0 },
		{ name: 'Weighted Dips', category: 'arms', defaultWeight: 10 },
		{ name: 'Skull Crushers', category: 'arms', defaultWeight: 10 },
		{ name: 'EZ Bar Skull Crushers', category: 'arms', defaultWeight: 15 },
		{ name: 'Dumbbell Skull Crushers', category: 'arms', defaultWeight: 8 },
		{ name: 'Close Grip Bench Press', category: 'arms', defaultWeight: 25 },
		{ name: 'Tricep Kickback', category: 'arms', defaultWeight: 6 },
		{ name: 'Cable Tricep Kickback', category: 'arms', defaultWeight: 8 },
		{ name: 'Diamond Push-ups', category: 'arms', defaultWeight: 0 },
		{ name: 'Tricep Machine', category: 'arms', defaultWeight: 25 },
		// Forearm exercises
		{ name: 'Wrist Curl', category: 'arms', defaultWeight: 10 },
		{ name: 'Reverse Wrist Curl', category: 'arms', defaultWeight: 8 },
		{ name: 'Farmers Walk', category: 'arms', defaultWeight: 20 },
		{ name: 'Plate Pinch', category: 'arms', defaultWeight: 10 },
		{ name: 'Dead Hang', category: 'arms', defaultWeight: 0 }
	],
	core: [
		// Machine and cable exercises
		{ name: 'Cable Crunch', category: 'core', defaultWeight: 30 },
		{ name: 'Kneeling Cable Crunch', category: 'core', defaultWeight: 30 },
		{ name: 'Ab Machine', category: 'core', defaultWeight: 25 },
		{ name: 'Ab Crunch Machine', category: 'core', defaultWeight: 25 },
		{ name: 'Torso Rotation', category: 'core', defaultWeight: 20 },
		{ name: 'Torso Rotation Machine', category: 'core', defaultWeight: 25 },
		{ name: 'Wood Chop', category: 'core', defaultWeight: 10 },
		{ name: 'Cable Wood Chop', category: 'core', defaultWeight: 15 },
		{ name: 'High to Low Wood Chop', category: 'core', defaultWeight: 12 },
		{ name: 'Low to High Wood Chop', category: 'core', defaultWeight: 12 },
		{ name: 'Pallof Press', category: 'core', defaultWeight: 10 },
		// Hanging exercises
		{ name: 'Hanging Leg Raise', category: 'core', defaultWeight: 0 },
		{ name: 'Hanging Knee Raise', category: 'core', defaultWeight: 0 },
		{ name: 'Hanging Oblique Raise', category: 'core', defaultWeight: 0 },
		{ name: 'Captain\'s Chair Leg Raise', category: 'core', defaultWeight: 0 },
		{ name: 'Toes to Bar', category: 'core', defaultWeight: 0 },
		{ name: 'Windshield Wipers', category: 'core', defaultWeight: 0 },
		// Floor exercises
		{ name: 'Plank', category: 'core', defaultWeight: 0 },
		{ name: 'Side Plank', category: 'core', defaultWeight: 0 },
		{ name: 'Weighted Plank', category: 'core', defaultWeight: 10 },
		{ name: 'Crunches', category: 'core', defaultWeight: 0 },
		{ name: 'Weighted Crunches', category: 'core', defaultWeight: 5 },
		{ name: 'Reverse Crunch', category: 'core', defaultWeight: 0 },
		{ name: 'Decline Crunch', category: 'core', defaultWeight: 0 },
		{ name: 'Russian Twist', category: 'core', defaultWeight: 5 },
		{ name: 'Weighted Russian Twist', category: 'core', defaultWeight: 8 },
		{ name: 'Leg Raise', category: 'core', defaultWeight: 0 },
		{ name: 'Lying Leg Raise', category: 'core', defaultWeight: 0 },
		{ name: 'Bicycle Crunches', category: 'core', defaultWeight: 0 },
		{ name: 'Mountain Climbers', category: 'core', defaultWeight: 0 },
		{ name: 'Dead Bug', category: 'core', defaultWeight: 0 },
		{ name: 'Bird Dog', category: 'core', defaultWeight: 0 },
		{ name: 'V-Ups', category: 'core', defaultWeight: 0 },
		{ name: 'Sit-ups', category: 'core', defaultWeight: 0 },
		{ name: 'Weighted Sit-ups', category: 'core', defaultWeight: 5 },
		{ name: 'Decline Sit-ups', category: 'core', defaultWeight: 0 },
		{ name: 'Flutter Kicks', category: 'core', defaultWeight: 0 },
		{ name: 'Scissor Kicks', category: 'core', defaultWeight: 0 },
		{ name: 'Heel Touches', category: 'core', defaultWeight: 0 },
		{ name: 'Toe Touches', category: 'core', defaultWeight: 0 },
		{ name: 'Ab Rollout', category: 'core', defaultWeight: 0 },
		{ name: 'Ab Wheel', category: 'core', defaultWeight: 0 },
		{ name: 'Hollow Hold', category: 'core', defaultWeight: 0 },
		{ name: 'L-Sit', category: 'core', defaultWeight: 0 },
		{ name: 'Dragon Flag', category: 'core', defaultWeight: 0 },
		// Back/core combo
		{ name: 'Superman', category: 'core', defaultWeight: 0 },
		{ name: 'Back Extension', category: 'core', defaultWeight: 0 }
	],
	cardio: [
		// Machines
		{ name: 'Treadmill', category: 'cardio' },
		{ name: 'Stationary Bike', category: 'cardio' },
		{ name: 'Recumbent Bike', category: 'cardio' },
		{ name: 'Upright Bike', category: 'cardio' },
		{ name: 'Spin Bike', category: 'cardio' },
		{ name: 'Elliptical', category: 'cardio' },
		{ name: 'Cross Trainer', category: 'cardio' },
		{ name: 'Rowing Machine', category: 'cardio' },
		{ name: 'Stair Climber', category: 'cardio' },
		{ name: 'StairMaster', category: 'cardio' },
		{ name: 'Step Mill', category: 'cardio' },
		{ name: 'Arc Trainer', category: 'cardio' },
		{ name: 'Ski Erg', category: 'cardio' },
		{ name: 'Assault Bike', category: 'cardio' },
		{ name: 'Air Bike', category: 'cardio' },
		{ name: 'Fan Bike', category: 'cardio' },
		{ name: 'VersaClimber', category: 'cardio' },
		{ name: 'Jacob\'s Ladder', category: 'cardio' },
		// Floor cardio
		{ name: 'Jump Rope', category: 'cardio' },
		{ name: 'Double Unders', category: 'cardio' },
		{ name: 'Burpees', category: 'cardio' },
		{ name: 'Jumping Jacks', category: 'cardio' },
		{ name: 'High Knees', category: 'cardio' },
		{ name: 'Butt Kicks', category: 'cardio' },
		{ name: 'Box Jumps', category: 'cardio' },
		{ name: 'Battle Ropes', category: 'cardio' },
		{ name: 'Sled Push', category: 'cardio' },
		{ name: 'Sled Pull', category: 'cardio' },
		{ name: 'Prowler Push', category: 'cardio' },
		{ name: 'Kettlebell Swings', category: 'cardio' },
		{ name: 'Running', category: 'cardio' },
		{ name: 'Sprints', category: 'cardio' },
		{ name: 'Walking', category: 'cardio' },
		{ name: 'Incline Walking', category: 'cardio' },
		{ name: 'HIIT', category: 'cardio' }
	],
	sports: [
		// Ball sports
		{ name: 'Swimming', category: 'sports' },
		{ name: 'Basketball', category: 'sports' },
		{ name: 'Soccer', category: 'sports' },
		{ name: 'Football', category: 'sports' },
		{ name: 'Tennis', category: 'sports' },
		{ name: 'Padel', category: 'sports' },
		{ name: 'Squash', category: 'sports' },
		{ name: 'Badminton', category: 'sports' },
		{ name: 'Table Tennis', category: 'sports' },
		{ name: 'Volleyball', category: 'sports' },
		{ name: 'Beach Volleyball', category: 'sports' },
		{ name: 'Golf', category: 'sports' },
		{ name: 'Baseball', category: 'sports' },
		{ name: 'Softball', category: 'sports' },
		{ name: 'Rugby', category: 'sports' },
		{ name: 'Hockey', category: 'sports' },
		{ name: 'Ice Hockey', category: 'sports' },
		{ name: 'Handball', category: 'sports' },
		// Combat sports
		{ name: 'Boxing', category: 'sports' },
		{ name: 'Kickboxing', category: 'sports' },
		{ name: 'MMA', category: 'sports' },
		{ name: 'Martial Arts', category: 'sports' },
		{ name: 'Jiu Jitsu', category: 'sports' },
		{ name: 'Karate', category: 'sports' },
		{ name: 'Taekwondo', category: 'sports' },
		{ name: 'Judo', category: 'sports' },
		{ name: 'Wrestling', category: 'sports' },
		{ name: 'Muay Thai', category: 'sports' },
		// Outdoor activities
		{ name: 'Hiking', category: 'sports' },
		{ name: 'Trail Running', category: 'sports' },
		{ name: 'Climbing', category: 'sports' },
		{ name: 'Rock Climbing', category: 'sports' },
		{ name: 'Bouldering', category: 'sports' },
		{ name: 'Cycling', category: 'sports' },
		{ name: 'Mountain Biking', category: 'sports' },
		{ name: 'Road Cycling', category: 'sports' },
		{ name: 'Skateboarding', category: 'sports' },
		{ name: 'Rollerblading', category: 'sports' },
		{ name: 'Surfing', category: 'sports' },
		{ name: 'Kayaking', category: 'sports' },
		{ name: 'Paddleboarding', category: 'sports' },
		{ name: 'Rowing', category: 'sports' },
		{ name: 'Skiing', category: 'sports' },
		{ name: 'Snowboarding', category: 'sports' },
		{ name: 'Cross Country Skiing', category: 'sports' },
		{ name: 'Ice Skating', category: 'sports' },
		// Fitness classes
		{ name: 'Yoga', category: 'sports' },
		{ name: 'Hot Yoga', category: 'sports' },
		{ name: 'Pilates', category: 'sports' },
		{ name: 'Reformer Pilates', category: 'sports' },
		{ name: 'Dancing', category: 'sports' },
		{ name: 'Zumba', category: 'sports' },
		{ name: 'Aerobics', category: 'sports' },
		{ name: 'CrossFit', category: 'sports' },
		{ name: 'Bootcamp', category: 'sports' },
		{ name: 'Spinning Class', category: 'sports' },
		{ name: 'Stretching', category: 'sports' },
		{ name: 'Mobility Work', category: 'sports' },
		// Other
		{ name: 'Gymnastics', category: 'sports' },
		{ name: 'Calisthenics', category: 'sports' },
		{ name: 'Parkour', category: 'sports' },
		{ name: 'Trampoline', category: 'sports' },
		{ name: 'Frisbee', category: 'sports' },
		{ name: 'Ultimate Frisbee', category: 'sports' }
	]
};

export const commonReps = [6, 8, 10, 12, 15, 20];
export const commonSets = [2, 3, 4, 5];
